name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure the latest version is in CHANGELOG
        run: |
          VERSION=${{ github.ref_name }}
          VERSION="${VERSION:1}"
          grep -q "## \[$VERSION\]" CHANGELOG.md || (echo "Version not found in CHANGELOG" && exit 1)

      - name: Fetch previous tag
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          git tag -l 'v*' | sort -V | tail -n 2 | head -n 1 > /tmp/previous-tag
          cat /tmp/previous-tag

      - name: Ensure the previous version is not in README
        run: |
          grep -q "$(cat /tmp/previous-tag)" README.md && (echo "Previous version found in README" && exit 1) || echo "Previous version not found in README"

      - name: Fetch the commit of the previous tag
        run: |
          git fetch --depth=1 origin $(cat /tmp/previous-tag)

      - name: Get diff
        run: |
          git diff $(cat /tmp/previous-tag)..HEAD -U10 CHANGELOG.md > /tmp/diff.txt
          cat /tmp/diff.txt

      - name: Setup defect
        uses: ./
        with:
          version: "0.3.2"

      - name: Review the diff
        env:
          OPENAI_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          OPENAI_API_BASE: https://api.deepseek.com/
        run: |
          diff=$(cat /tmp/diff.txt)

          prompt="
          You are a coding expert.
          Review the following diff, only ensure that:
          - For CHANGELOG
            - Nothing is under [Unreleased] section. The section should exist but be empty.
            - The version number of the latest section is correct.
            - Links at the bottom are updated and correct.
            - All "Added"/"Changed"/"Fixed"/"Removed" etc sections are h3.
          - Ignore all other files.

          If you think the diff is correct, output 'OK' with nothing else.
          Otherwise, output suggestions in markdown format.

          <latest_version>
          ${{ github.ref_name }}
          </latest_version>

          <diff>
          $diff
          </diff>
          "

          defect --model=deepseek-chat "$prompt" > /tmp/suggestions
          cat /tmp/suggestions

      - name: Abort if suggestions are not empty
        run: |
          suggestions=$(cat /tmp/suggestions)

          if [ "$suggestions" != "OK" ]; then
            exit 1
          fi

      - name: Create release
        run: gh release create ${{ github.ref_name }} -t ${{ github.ref_name }} --verify-tag -n "See [CHANGELOG.md](https://github.com/DiscreteTom/setup-defect/blob/main/CHANGELOG.md)."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
